CREATE TABLE POSTS(
ID INT (10) NOT NULL AUTO_INCREMENT,
TITLE VARCHAR(50),
CONTENT VARCHAR(255),
CREATED_AT TIMESTAMP,
COMMENT_ID INT (10),
PRIMARY KEY(ID),
FOREIGN KEY(COMMENT_ID) REFERENCES POSTS(ID)
);